#! /usr/bin/env bash

# The ACM SIGCOMM 2012 Website (of which this script is a part of) by 
# ACM SIGCOMM 2012 is licensed under a Creative Commons Attribution-
# NonCommercial-ShareAlike 3.0 Unported License. Source code is
# available at github.com.

# for all local files, do...
ls *.php *.html *.htm| while read item
do
	# fetch the HTML from the local PHP testing server
	src=$(mktemp /tmp/XXXXXXXXXX)
	url=http://127.0.0.1:8000/$item
	echo "----------------------------------------------------------"
	echo $url
	curl -s $url -o $src

	# run it through a version of tidy that groks HTML5
	err=$(mktemp /tmp/XXXXXXXXXX)
	~/Documents/Code/tidy-html5/bin/tidy -eq $src > $err 2>&1

	# find the error messages
	cat $err | while read msg
	do
		line=$(echo $msg | cut -f2 -d" ")		
		# and print them together with the corresponding source line(s)
		if [[ $line =~ [0-9]+ && ! $msg =~ "proprietary attribute" ]]; then
			echo "***" $msg
			sed -n "$(($line-2)),$(($line+2))p" $src
			echo
		fi
	done
	
	perl -ne 'print "$. $_" if m/[\x80-\xFF]/' $item
	
	echo	
	rm $err $src
done
